/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e4e9ec",
        "on-surface-variant": "#5a6064",
        "secondary-dim": "#00603e",
        "tertiary-dim": "#5f4b73",
        "secondary-fixed-dim": "#7fe9b4",
        "on-error-container": "#6e0a12",
        "surface-dim": "#d5dbdf",
        "error-container": "#fa746f",
        "error-dim": "#67040d",
        "secondary-container": "#8df7c1",
        "surface-bright": "#f8f9fb",
        "surface-container": "#ebeef1",
        "on-background": "#2d3337",
        "on-primary-container": "#000000",
        "secondary": "#006d48",
        "on-primary-fixed-variant": "#000e32",
        "on-primary-fixed": "#000000",
        "tertiary-fixed-dim": "#dabfef",
        "secondary-fixed": "#8df7c1",
        "on-tertiary-fixed": "#433056",
        "primary-dim": "#004bbc",
        "on-secondary-fixed-variant": "#006945",
        "on-error": "#fff7f6",
        "on-tertiary-container": "#57426a",
        "background": "#f8f9fb",
        "on-secondary-container": "#005e3d",
        "tertiary-container": "#e8cdfd",
        "primary-fixed": "#4e83fe",
        "on-tertiary-fixed-variant": "#614c74",
        "surface": "#f8f9fb",
        "on-tertiary": "#fff6ff",
        "on-primary": "#f9f8ff",
        "surface-container-highest": "#dee3e7",
        "inverse-on-surface": "#9b9d9f",
        "primary": "#0f57d0",
        "primary-fixed-dim": "#3f75f0",
        "tertiary-fixed": "#e8cdfd",
        "surface-container-low": "#f1f4f7",
        "on-secondary-fixed": "#00492f",
        "tertiary": "#6c567f",
        "inverse-surface": "#0c0f10",
        "outline-variant": "#adb3b7",
        "on-secondary": "#e6ffee",
        "primary-container": "#4e83fe",
        "outline": "#767b7f",
        "on-surface": "#2d3337",
        "surface-tint": "#0f57d0",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#5c8bff",
        "error": "#a83836",
        "surface-variant": "#dee3e7",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
