import type { Job, Worker, DashboardStats, Post, Notification, Rating } from '../types';

// ─── Mock Jobs ────────────────────────────
export const MOCK_JOBS: Job[] = [
  {
    id: '1',
    title: 'Lead Electrical Supervisor',
    company: 'Mehta Construction Group',
    location: 'Mumbai, MH',
    wage: '₹2,800',
    wageUnit: 'day',
    skills: ['Electrician', 'Industrial Power', 'Blueprints'],
    description: 'Seeking an experienced supervisor for a township project in Bandra. Must have 5+ years experience in large-scale residential cabling and switchgear installation.',
    postedAt: '2 hours ago',
    status: 'open',
    icon: 'bolt',
    likes: 14,
    comments: 3,
    type: 'immediate',
    postedBy: 'contractor',
  },
  {
    id: '2',
    title: 'Skilled Mason for Ornamental Stone Work',
    company: 'GreenScape Designs',
    location: 'Pune, MH',
    wage: '₹3,500',
    wageUnit: 'day',
    skills: ['Masonry', 'Stone Cutting'],
    description: 'Looking for detail-oriented masons for a luxury garden project. High precision work required for interlocking stone pathways and marble water features.',
    postedAt: '5 hours ago',
    status: 'open',
    icon: 'construction',
    likes: 32,
    comments: 8,
    type: 'contract',
    postedBy: 'contractor',
  },
  {
    id: '3',
    title: 'Senior Formwork Carpenter',
    company: 'Metro Infrastructure',
    location: 'Downtown',
    wage: '₹2,200',
    wageUnit: 'day',
    skills: ['Carpentry', 'Formwork', 'Safety'],
    description: 'Leading infrastructure project requires experienced formwork carpenters for the new city bypass construction.',
    postedAt: '1 day ago',
    status: 'open',
    icon: 'architecture',
    likes: 20,
    comments: 5,
    type: 'immediate',
  },
  {
    id: '4',
    title: 'Licensed Electrician',
    company: 'Bright Future Builders',
    location: 'North Suburbs',
    wage: '₹2,600',
    wageUnit: 'day',
    skills: ['Electrical', 'Wiring', 'Certification'],
    description: 'Residential wiring for a new multi-unit development. Must have own tools and valid safety certification.',
    postedAt: '2 days ago',
    status: 'open',
    icon: 'electric_bolt',
    likes: 11,
    comments: 2,
    type: 'contract',
  },
  {
    id: '5',
    title: 'Maintenance Plumber',
    company: 'City Works Corp',
    location: 'Industrial Park',
    wage: '₹2,400',
    wageUnit: 'day',
    skills: ['Plumbing', 'Maintenance', 'Fitting'],
    description: 'Urgent repair work for a commercial complex. Shift work available (mornings or evenings).',
    postedAt: '3 days ago',
    status: 'open',
    icon: 'plumbing',
    likes: 7,
    comments: 1,
    type: 'immediate',
  },
  {
    id: '6',
    title: 'Interior Finisher',
    company: 'Prestige Homes',
    location: 'West Side',
    wage: '₹1,900',
    wageUnit: 'day',
    skills: ['Painting', 'Finishing', 'Detailing'],
    description: 'High-end residential painting and finishing. Attention to detail is critical. Long term contract.',
    postedAt: '4 days ago',
    status: 'open',
    icon: 'format_paint',
    likes: 15,
    comments: 4,
    type: 'contract',
  },
];

// ─── Mock Dashboard Jobs (Contractor side) ────────────────────────────
export const CONTRACTOR_JOBS: Job[] = [
  {
    id: 'c1',
    title: 'Senior Site Foreman',
    company: 'My Company',
    location: 'Downtown Metro Project',
    wage: '$45 - $55',
    wageUnit: 'hr',
    skills: ['Foreman', 'Safety'],
    description: 'Oversee a flagship construction project.',
    postedAt: '2 days ago',
    status: 'open',
    icon: 'engineering',
    applicants: 24,
    type: 'immediate',
  },
  {
    id: 'c2',
    title: 'Journeyman Electrician',
    company: 'My Company',
    location: 'Westside Residential',
    wage: '$38 - $42',
    wageUnit: 'hr',
    skills: ['Electrical'],
    description: 'Residential electrical work for new development.',
    postedAt: '5 days ago',
    status: 'open',
    icon: 'bolt',
    applicants: 12,
  },
  {
    id: 'c3',
    title: 'General Laborer (Day Shift)',
    company: 'My Company',
    location: 'Industrial Park',
    wage: '$22',
    wageUnit: 'hr',
    skills: ['General Labor'],
    description: 'Day shift general labor work.',
    postedAt: '1 week ago',
    status: 'open',
    icon: 'construction',
    applicants: 48,
  },
];

// ─── Mock Worker Profile ────────────────────────────
export const MOCK_WORKER: Worker = {
  id: 'w1',
  name: 'Arjun Sharma',
  title: 'Master Electrician',
  location: 'Mumbai, MH',
  trustScore: 4.5,
  jobsCompleted: 15,
  profileViews: 142,
  rating: 4.9,
  verified: true,
  about: 'Experienced Master Electrician with over 8 years of hands-on expertise in residential and industrial electrical systems. Certified in HVAC repair and advanced wiring. Committed to safety, quality, and professionalism on every project.',
  skills: ['Electrical Wiring', 'HVAC Repair', 'Industrial Power', 'Blueprints', 'Panel Upgrade', 'Smart Lighting', 'Circuit Repair', 'Plumbing'],
  followers: 238,
  following: 142,
  referralCode: 'ARJUN-LL-2024',
  endorsements: [
    { skill: 'Wiring', count: 24, endorsedBy: 'Mehta Construction' },
    { skill: 'Mason', count: 10, endorsedBy: 'BuildCorp Ltd' },
    { skill: 'HVAC Repair', count: 8, endorsedBy: 'City Works Corp' },
    { skill: 'Plumbing', count: 5, endorsedBy: 'GreenScape Designs' },
  ],
  portfolio: [
    { id: 'p1', title: 'Main Panel Upgrade', imageUrl: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=400&q=80' },
    { id: 'p2', title: 'Smart Lighting', imageUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=400&q=80' },
    { id: 'p3', title: 'Commercial Setup', imageUrl: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&q=80' },
  ],
  recentJobs: [
    { id: 'rj1', title: 'Full House Rewiring', completedDate: 'Oct 12, 2023', rating: 5, ratingLabel: 'Perfect Rating', icon: 'bolt' },
    { id: 'rj2', title: 'LED Fixture Installation', completedDate: 'Sept 28, 2023', rating: 4, ratingLabel: 'High Quality', icon: 'lightbulb' },
    { id: 'rj3', title: 'Emergency Circuit Repair', completedDate: 'Sept 15, 2023', rating: 5, ratingLabel: 'Fast Response', icon: 'construction' },
  ],
};

// ─── Mock Dashboard Stats ────────────────────────────
export const MOCK_STATS: DashboardStats = {
  activeJobs: 12,
  applicants: 84,
  totalHires: 342,
  earnings: 142500,
  jobsThisWeek: 6,
};

// ─── Mock Feed Posts ────────────────────────────
export const MOCK_POSTS: Post[] = [
  {
    id: 'post1',
    author: 'Arjun Sharma',
    authorTitle: 'Master Electrician',
    content: 'Just completed a major panel upgrade in Bandra! 3-day project, flawless execution. Grateful to the team. 🔧⚡',
    location: 'Bandra, Mumbai',
    postedAt: '1 hour ago',
    likes: 42,
    comments: 8,
  },
  {
    id: 'post2',
    author: 'Priya Mehta',
    authorTitle: 'Contractor · Mehta Group',
    content: 'We are hiring 5 senior electricians for our new township project in Bandra. Great pay, verified employer. Apply via LabourLink!',
    postedAt: '3 hours ago',
    likes: 89,
    comments: 22,
  },
];

// ─── Mock Notifications ────────────────────────────
export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif1',
    type: 'job',
    title: 'Job application status updated',
    message: 'Your application for "Senior Site Manager" has been moved to the interview stage.',
    time: '2 hours ago',
    read: false,
    icon: 'work',
  },
  {
    id: 'notif2',
    type: 'rating',
    title: 'New rating received',
    message: 'BuildCorp Ltd rated you 5.0',
    time: '5 hours ago',
    read: false,
    icon: 'star',
  },
  {
    id: 'notif3',
    type: 'follower',
    title: 'Sarah Jenkins followed you',
    message: "Check out Sarah's network of trade professionals.",
    time: 'Yesterday',
    read: true,
    icon: 'person_add',
  },
  {
    id: 'notif4',
    type: 'payment',
    title: 'Payment released',
    message: 'The milestone payment for "Plumbing Overhaul" has been processed.',
    time: '2 days ago',
    read: true,
    icon: 'payments',
  },
  {
    id: 'notif5',
    type: 'endorsement',
    title: 'New endorsement received',
    message: 'Mehta Construction endorsed you for Wiring.',
    time: '3 days ago',
    read: true,
    icon: 'military_tech',
  },
];

// ─── Mock Ratings ────────────────────────────
export const MOCK_RATINGS: Rating[] = [
  {
    id: 'r1',
    workerId: 'w1',
    workerName: 'Marcus Chen',
    contractorName: 'BuildCorp Ltd',
    score: 5,
    strengths: ['Punctual', 'Expert Knowledge'],
    comment: 'Exceptional work on the industrial rewiring project. Marcus demonstrated outstanding professionalism and technical skill.',
    createdAt: '2 weeks ago',
  },
  {
    id: 'r2',
    workerId: 'w1',
    workerName: 'Marcus Chen',
    contractorName: 'City Works Corp',
    score: 4,
    strengths: ['Clean Workspace', 'Communication'],
    comment: 'Great job on the LED fixture installation. Communication was clear throughout the project.',
    createdAt: '1 month ago',
  },
  {
    id: 'r3',
    workerId: 'w1',
    workerName: 'Marcus Chen',
    contractorName: 'Prestige Homes',
    score: 5,
    strengths: ['Punctual', 'Clean Workspace', 'Expert Knowledge'],
    comment: 'Marcus completed the emergency circuit repair ahead of schedule. Highly recommended!',
    createdAt: '2 months ago',
  },
];

export const NEWS_ITEMS = [
  { id: 'n1', title: 'New Safety Guidelines for 2024', time: '4d ago', readers: '1,202' },
  { id: 'n2', title: 'Govt. announces Skill Bonus scheme', time: '2d ago', readers: '850' },
  { id: 'n3', title: 'The rise of Modular Prefabrication', time: '1d ago', readers: '340' },
];

// ─── Available Skills for Selection ────────────────────────────
export const AVAILABLE_SKILLS = [
  { name: 'Plumbing', icon: 'plumbing', color: 'bg-blue-50', iconColor: 'text-blue-600', hoverBg: 'group-hover:bg-primary-container' },
  { name: 'Electrical', icon: 'bolt', color: 'bg-amber-50', iconColor: 'text-amber-600', hoverBg: 'group-hover:bg-amber-400' },
  { name: 'Landscaping', icon: 'grass', color: 'bg-emerald-50', iconColor: 'text-emerald-600', hoverBg: 'group-hover:bg-secondary' },
  { name: 'Cleaning', icon: 'cleaning_services', color: 'bg-cyan-50', iconColor: 'text-cyan-600', hoverBg: 'group-hover:bg-cyan-500' },
  { name: 'Construction', icon: 'construction', color: 'bg-orange-50', iconColor: 'text-orange-600', hoverBg: 'group-hover:bg-orange-500' },
  { name: 'Carpentry', icon: 'carpenter', color: 'bg-stone-100', iconColor: 'text-stone-600', hoverBg: 'group-hover:bg-stone-500' },
  { name: 'Painting', icon: 'format_paint', color: 'bg-purple-50', iconColor: 'text-purple-600', hoverBg: 'group-hover:bg-purple-500' },
  { name: 'Masonry', icon: 'home_work', color: 'bg-red-50', iconColor: 'text-red-600', hoverBg: 'group-hover:bg-red-600' },
];
