import type { Job, Worker, DashboardStats, Post } from '../types';

// ─── Mock Jobs ────────────────────────────
export const MOCK_JOBS: Job[] = [
  {
    id: '1',
    title: 'Lead Electrical Supervisor',
    company: 'Mehta Construction Group',
    location: 'Mumbai, MH',
    wage: '₹2,800',
    wageUnit: 'day',
    skills: ['Electrician', 'Industrial Power', 'Blueprints'],
    description: 'Seeking an experienced supervisor for a township project in Bandra. Must have 5+ years experience in large-scale residential cabling and switchgear installation.',
    postedAt: '2 hours ago',
    status: 'open',
    icon: 'bolt',
    likes: 14,
    comments: 3,
    type: 'immediate',
  },
  {
    id: '2',
    title: 'Skilled Mason for Ornamental Stone Work',
    company: 'GreenScape Designs',
    location: 'Pune, MH',
    wage: '₹3,500',
    wageUnit: 'day',
    skills: ['Masonry', 'Stone Cutting'],
    description: 'Looking for detail-oriented masons for a luxury garden project. High precision work required for interlocking stone pathways and marble water features.',
    postedAt: '5 hours ago',
    status: 'open',
    icon: 'construction',
    likes: 32,
    comments: 8,
    type: 'contract',
  },
  {
    id: '3',
    title: 'Senior Formwork Carpenter',
    company: 'Metro Infrastructure',
    location: 'Downtown',
    wage: '₹2,200',
    wageUnit: 'day',
    skills: ['Carpentry', 'Formwork', 'Safety'],
    description: 'Leading infrastructure project requires experienced formwork carpenters for the new city bypass construction.',
    postedAt: '1 day ago',
    status: 'open',
    icon: 'architecture',
    likes: 20,
    comments: 5,
    type: 'immediate',
  },
  {
    id: '4',
    title: 'Licensed Electrician',
    company: 'Bright Future Builders',
    location: 'North Suburbs',
    wage: '₹2,600',
    wageUnit: 'day',
    skills: ['Electrical', 'Wiring', 'Certification'],
    description: 'Residential wiring for a new multi-unit development. Must have own tools and valid safety certification.',
    postedAt: '2 days ago',
    status: 'open',
    icon: 'electric_bolt',
    likes: 11,
    comments: 2,
    type: 'contract',
  },
  {
    id: '5',
    title: 'Maintenance Plumber',
    company: 'City Works Corp',
    location: 'Industrial Park',
    wage: '₹2,400',
    wageUnit: 'day',
    skills: ['Plumbing', 'Maintenance', 'Fitting'],
    description: 'Urgent repair work for a commercial complex. Shift work available (mornings or evenings).',
    postedAt: '3 days ago',
    status: 'open',
    icon: 'plumbing',
    likes: 7,
    comments: 1,
    type: 'immediate',
  },
  {
    id: '6',
    title: 'Interior Finisher',
    company: 'Prestige Homes',
    location: 'West Side',
    wage: '₹1,900',
    wageUnit: 'day',
    skills: ['Painting', 'Finishing', 'Detailing'],
    description: 'High-end residential painting and finishing. Attention to detail is critical. Long term contract.',
    postedAt: '4 days ago',
    status: 'open',
    icon: 'format_paint',
    likes: 15,
    comments: 4,
    type: 'contract',
  },
];

// ─── Mock Dashboard Jobs (Contractor side) ────────────────────────────
export const CONTRACTOR_JOBS: Job[] = [
  {
    id: 'c1',
    title: 'Senior Masonry Specialist',
    company: 'My Company',
    location: 'Downtown District',
    wage: '₹2,250',
    wageUnit: 'hr',
    skills: ['Masonry'],
    description: '',
    postedAt: '2 hours ago',
    status: 'open',
    icon: 'architecture',
    applicants: 15,
  },
  {
    id: 'c2',
    title: 'Industrial Electrician',
    company: 'My Company',
    location: 'Port Authority',
    wage: '₹2,600',
    wageUnit: 'hr',
    skills: ['Electrical'],
    description: '',
    postedAt: '1 day ago',
    status: 'open',
    icon: 'bolt',
    applicants: 7,
  },
  {
    id: 'c3',
    title: 'General Painter (x5)',
    company: 'My Company',
    location: 'Westview Mall',
    wage: '₹1,400',
    wageUnit: 'hr',
    skills: ['Painting'],
    description: '',
    postedAt: '5 days ago',
    status: 'closed',
    icon: 'format_paint',
    applicants: 5,
  },
];

// ─── Mock Worker Profile ────────────────────────────
export const MOCK_WORKER: Worker = {
  id: 'w1',
  name: 'Arjun Sharma',
  title: 'Master Electrician',
  location: 'Mumbai, MH',
  trustScore: 4.5,
  jobsCompleted: 15,
  profileViews: 142,
  rating: 4.9,
  verified: true,
  followers: 238,
  following: 142,
  referralCode: 'ARJUN-LL-2024',
  endorsements: [
    { skill: 'Wiring', count: 24 },
    { skill: 'Mason', count: 10 },
    { skill: 'HVAC Repair', count: 8 },
    { skill: 'Plumbing', count: 5 },
  ],
  portfolio: [
    { id: 'p1', title: 'Main Panel Upgrade', imageUrl: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=400&q=80' },
    { id: 'p2', title: 'Smart Lighting', imageUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=400&q=80' },
    { id: 'p3', title: 'Commercial Setup', imageUrl: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&q=80' },
  ],
  recentJobs: [
    { id: 'rj1', title: 'Full House Rewiring', completedDate: 'Oct 12, 2023', rating: 5, ratingLabel: 'Perfect Rating', icon: 'bolt' },
    { id: 'rj2', title: 'LED Fixture Installation', completedDate: 'Sept 28, 2023', rating: 4, ratingLabel: 'High Quality', icon: 'lightbulb' },
    { id: 'rj3', title: 'Emergency Circuit Repair', completedDate: 'Sept 15, 2023', rating: 5, ratingLabel: 'Fast Response', icon: 'construction' },
  ],
};

// ─── Mock Dashboard Stats ────────────────────────────
export const MOCK_STATS: DashboardStats = {
  activeJobs: 24,
  applicants: 148,
  totalHires: 892,
  earnings: 142500,
  jobsThisWeek: 6,
};

// ─── Mock Feed Posts ────────────────────────────
export const MOCK_POSTS: Post[] = [
  {
    id: 'post1',
    author: 'Arjun Sharma',
    authorTitle: 'Master Electrician',
    content: 'Just completed a major panel upgrade in Bandra! 3-day project, flawless execution. Grateful to the team. 🔧⚡',
    location: 'Bandra, Mumbai',
    postedAt: '1 hour ago',
    likes: 42,
    comments: 8,
  },
  {
    id: 'post2',
    author: 'Priya Mehta',
    authorTitle: 'Contractor · Mehta Group',
    content: 'We are hiring 5 senior electricians for our new township project in Bandra. Great pay, verified employer. Apply via LabourLink!',
    postedAt: '3 hours ago',
    likes: 89,
    comments: 22,
  },
];

export const NEWS_ITEMS = [
  { id: 'n1', title: 'New Safety Guidelines for 2024', time: '4d ago', readers: '1,202' },
  { id: 'n2', title: 'Govt. announces Skill Bonus scheme', time: '2d ago', readers: '850' },
  { id: 'n3', title: 'The rise of Modular Prefabrication', time: '1d ago', readers: '340' },
];
